/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/skull/scene.gltf 
Author: martinjario (https://sketchfab.com/martinjario)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skull-downloadable-1a9db900738d44298b0bc59f68123393
Title: Skull downloadable
*/

import { useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Skull(props) {
  const { nodes, materials } = useGLTF("public/skull/scene.gltf");

  const obsidianMaterial = useMemo(
    () =>
      new THREE.MeshPhysicalMaterial({
        color: "#000000",
        roughness: 0.1, // glassy but not mirror
        metalness: 0,
        clearcoat: 0,
        clearcoatRoughness: 0.03,
        reflectivity: 0.1,
        envMapIntensity: 2.5,
        ior: 1.25, // glass, not diamond
        transmission: 0.05, // VERY subtle depth
        thickness: 0.5,
      }),
    []
  );
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, 0, 1.3]}
        scale={0.693}
        position={[0, 0 - 0.0, 1]}
      >
        {Object.values(nodes).map((node) =>
          node.geometry ? (
            <mesh geometry={node.geometry} material={obsidianMaterial} />
          ) : null
        )}
      </group>
    </group>
  );
}

useGLTF.preload("public/skull/scene.gltf");
