/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/skull_set/scene.gltf 
Author: ℜ𝔢𝔞𝔩 𝔖𝔩𝔦𝔪 𝔖𝔥𝔞𝔡𝔶 (https://sketchfab.com/real_slimshady)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skull-set-4133909f559848cfb7aaac81a795fba9
Title: Skull Set
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Skull(props) {
  const { nodes, materials } = useGLTF("/public/skull_set/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={[8, 8, 8]} rotation={[-Math.PI / 2, 0, Math.PI]}>
        <mesh
          geometry={nodes["Material1-material_002-material"].geometry}
          material={materials["Material1-material.002"]}
          position={[0.515, 0.006, -0.051]}
          rotation={[-0.007, -0.003, 3.109]}
          scale={[0.747, 0.193, 2.039]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/public/skull_set/scene.gltf");
