[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "https://skeletin.netlify.app/*"
  to = "https://skeletin.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://skeletin.netlify.app"
  to = "https://skeletin.dev"
  status = 301
  force = true

[[redirects]]
  from = "/api/projects"
  to = "/.netlify/functions/projects"
  status = 200

[[redirects]]
  from = "/api/projects/"
  to = "/.netlify/functions/projects"
  status = 200

[[redirects]]
  from = "/api/projects/:id"
  to = "/.netlify/functions/project?id=:id"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200