
export const mockProjects = [
  {
    id: "1",
    name: "Nebula Stream",
    year: "2024",
    description: "A high-performance real-time data streaming platform visualizing cosmic events.",
    repoUrl: "https://github.com/skeletin/nebula-stream",
    siteUrl: "https://nebula-stream.demo",
    displayPictureUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?q=80&w=2000&auto=format&fit=crop",
    techStack: ["reactjs", "nodejs", "socketio", "threejs"],
    projectType: "personal",
  },
  {
    id: "2",
    name: "Quantum Ledger",
    year: "2023",
    description: "Decentralized finance dashboard with quantum-resistant encryption algorithms.",
    repoUrl: "https://github.com/skeletin/quantum-ledger",
    siteUrl: "https://quantum-ledger.demo",
    displayPictureUrl: "https://images.unsplash.com/photo-1639322537228-ad71053db4bf?q=80&w=2000&auto=format&fit=crop",
    techStack: ["solidity", "ethereum", "nextjs", "tailwindcss"],
    projectType: "personal",
  },
  {
    id: "3",
    name: "Cyber Garden",
    year: "2023",
    description: "IoT automated plant care system with AI-driven growth analysis.",
    repoUrl: "https://github.com/skeletin/cyber-garden",
    siteUrl: null,
    displayPictureUrl: "https://images.unsplash.com/photo-1530893609608-32a9af3aa95c?q=80&w=2000&auto=format&fit=crop",
    techStack: ["python", "raspberrypi", "tensorflow", "flutter"],
    projectType: "personal",
  },
  {
    id: "4",
    name: "Void Messenger",
    year: "2022",
    description: "End-to-end encrypted messaging app that stores no metadata.",
    repoUrl: "https://github.com/skeletin/void-messenger",
    siteUrl: "https://void.chat",
    displayPictureUrl: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?q=80&w=2000&auto=format&fit=crop",
    techStack: ["rust", "webassembly", "redis", "reactjs"],
    projectType: "personal",
  },
  {
    id: "5",
    name: "Synthetix UI",
    year: "2024",
    description: "A component library for building cyberpunk-themed interfaces.",
    repoUrl: "https://github.com/skeletin/synthetix-ui",
    siteUrl: "https://synthetix.ui",
    displayPictureUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=2000&auto=format&fit=crop",
    techStack: ["typescript", "reactjs", "storybook", "sass"],
    projectType: "personal",
  },
  {
    id: "6",
    name: "Echo Analytics",
    year: "2021",
    description: "Big data visualization tool for social media sentiment analysis.",
    repoUrl: null,
    siteUrl: "https://echo.analytics",
    displayPictureUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2000&auto=format&fit=crop",
    techStack: ["d3js", "vuejs", "django", "postgresql"],
    projectType: "professional",
  },
    {
    id: "7",
    name: "Neon Racer",
    year: "2025",
    description: "Browser-based racing game with retro-wave aesthetics.",
    repoUrl: "https://github.com/skeletin/neon-racer",
    siteUrl: "https://neon-racer.game",
    displayPictureUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=2000&auto=format&fit=crop",
    techStack: ["javascript", "html5", "phaser", "webpack"],
    projectType: "personal",
  },
  {
    id: "8",
    name: "HoloOps",
    year: "2024",
    description: "AR interface for server infrastructure monitoring.",
    repoUrl: "https://github.com/skeletin/holo-ops",
    siteUrl: null,
    displayPictureUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2000&auto=format&fit=crop",
    techStack: ["csharp", "unity", "azure", "docker"],
    projectType: "professional",
  }
];
